/*
 *
 * Dashboard constants
 *
 */

export const SEARCH_ACTION = 'app/Dashboard/SEARCH_ACTION';

export const SEARCH_RESULTS_UPDATE_ACTION = 'app/Dashboard/SEARCH_RESULTS_UPDATE_ACTION';

export const REQUEST_COLLECTIONS_LIST_ACTION = 'app/Dashboard/REQUEST_COLLECTIONS_LIST_ACTION';

export const UPDATE_COLLECTIONS_LIST_ACTION = 'app/Dashboard/UPDATE_COLLECTIONS_LIST_ACTION';

export const CREATE_COLLECTION_ACTION = 'app/Dashboard/CREATE_COLLECTION_ACTION';
