#!/bin/bash

SESSION=$USER

#Import configurations from config.json.
export API_PORT=$(cat config.json | jq '.api_port')
export API_BASE=$(cat config.json | jq '.api_base_url')
export API_DOMAIN=$(cat config.json | jq '.api_host')

export UI_PORT=$(cat config.json | jq '.ui_port')
export UI_DOMAIN=$(cat config.json | jq '.ui_host')


# -2: forces 256 colors,
byobu-tmux -2 new-session -d -s $SESSION

# dev window
byobu-tmux rename-window -t $SESSION:0 'Dev'
byobu-tmux split-window  -v
byobu-tmux split-window  -v
byobu-tmux split-window  -h

# Select 1st pane cd and venv
byobu-tmux select-pane -t 0
byobu-tmux send-keys "./node_modules/nodemon/bin/nodemon.js ./index.js" C-m
#byobu-tmux send-keys "clear" C-m

# Same with 2nd pane
byobu-tmux select-pane -t 1
byobu-tmux send-keys "./node_modules/gulp/bin/gulp.js watch" C-m

# Work preview on 3rd pane
byobu-tmux select-pane -t 2
BANNER="

Press Enter at this pan to work
\n
Session Exit keyboard shortcut sequence:
----------------------------------------
  [Ctrl] + a, k
Another format:
  Ctrl-a k - Kill the current window

More information about byobu:
-----------------------------
  cat /usr/share/doc/byobu/help.tmux.txt
  https://www.byobu.org/documentation
  https://github.com/felixdrp/byobu-howto

"
byobu-tmux run-shell -b -t 2 "echo -e \"$BANNER\""

# byobu-tmux display-message -t 2 "This is #{window_name} in #{session_name}."
# byobu-tmux send 'htop -t' ENTER; 

# UI on 4th pane
byobu-tmux select-pane -t 3
byobu-tmux send-keys "cd ../UI" C-m
byobu-tmux send-keys "npm start" C-m
#byobu-tmux send-keys "watchify --debug ./build/gms-client.js -o public/lib/bundle.js" C-m

byobu-tmux select-layout even-vertical

# Runserver window next
#byobu-tmux new-window -t $SESSION:1 -n 'Runserver'
#byobu-tmux send-keys "cd /path/to/workingdir" C-m
#byobu-tmux send-keys 'source venv/bin/activate' C-m


# Set default window as the dev split plane
byobu-tmux select-window -t $SESSION:0

# Attach to the session you just created
# (flip between windows with alt -left and right)
byobu-tmux -2 attach-session -t $SESSION
