/*
 *
 * Annotator constants
 *
 */

// LOAD elements from backend
export const LOAD_TABLE_CONTENT_ACTION = 'app/Annotator/LOAD_TABLE_CONTENT_ACTION';
export const LOAD_TABLE_RESULTS_ACTION = 'app/Annotator/LOAD_TABLE_RESULTS_ACTION';
export const LOAD_TABLE_METADATA_ACTION = 'app/Annotator/LOAD_TABLE_METADATA_ACTION';
export const LOAD_TABLE_ANNOTATIONS_ACTION = 'app/Annotator/LOAD_TABLE_ANNOTATIONS_ACTION';

// Show elements in UI
export const UPDATE_TABLE_CONTENT_ACTION = 'app/Annotator/UPDATE_TABLE_CONTENT_ACTION';
export const UPDATE_TABLE_RESULTS_ACTION = 'app/Annotator/UPDATE_TABLE_RESULTS_ACTION';
export const UPDATE_TABLE_METADATA_ACTION = 'app/Annotator/UPDATE_TABLE_METADATA_ACTION';
export const UPDATE_TABLE_ANNOTATIONS_ACTION = 'app/Annotator/UPDATE_TABLE_ANNOTATIONS_ACTION';

// Communicate with Backend and save elements
export const SAVE_TABLE_TEXT_ACTION = 'app/Annotator/SAVE_TABLE_TEXT_ACTION';
export const SAVE_TABLE_NOTES_ACTION = 'app/Annotator/SAVE_TABLE_NOTES_ACTION';
export const SAVE_TABLE_ANNOTATIONS_ACTION = 'app/Annotator/SAVE_TABLE_ANNOTATIONS_ACTION';
// export const SAVE_TABLE_RESULTS_ACTION = 'app/Annotator/SAVE_TABLE_RESULTS_ACTION';
export const SAVE_TABLE_METADATA_ACTION = 'app/Annotator/SAVE_TABLE_METADATA_ACTION';

export const LOAD_CUIS_INDEX_ACTION = 'app/Annotator/LOAD_CUIS_INDEX_ACTION';
export const UPDATE_CUIS_INDEX_ACTION = 'app/Annotator/UPDATE_CUIS_INDEX_ACTION';
export const INSERT_CUIS_INDEX_ACTION = 'app/Annotator/INSERT_CUIS_INDEX_ACTION';
export const DELETE_CUIS_INDEX_ACTION = 'app/Annotator/DELETE_CUIS_INDEX_ACTION';

export const AUTO_LABEL_HEADERS_ACTION = 'app/Annotator/AUTO_LABEL_HEADERS_ACTION';

// export const LOAD_TABLE_CONTENT_ACTION = 'app/Annotator/LOAD_TABLE_CONTENT_ACTION';
// export const LOAD_TABLE_CONTENT_ACTION = 'app/Annotator/LOAD_TABLE_CONTENT_ACTION';
// export const LOAD_TABLE_CONTENT_ACTION = 'app/Annotator/LOAD_TABLE_CONTENT_ACTION';
// export const LOAD_TABLE_CONTENT_ACTION = 'app/Annotator/LOAD_TABLE_CONTENT_ACTION';
// export const LOAD_TABLE_CONTENT_ACTION = 'app/Annotator/LOAD_TABLE_CONTENT_ACTION';

// export const LOAD_COLLECTION_ACTION = 'app/CollectionView/LOAD_COLLECTION_ACTION';
// export const UPDATE_COLLECTION_ACTION = 'app/CollectionView/UPDATE_COLLECTION_ACTION';
// export const EDIT_COLLECTION_ACTION = 'app/CollectionView/EDIT_COLLECTION_ACTION';
// export const DELETE_COLLECTION_ACTION = 'app/CollectionView/DELETE_COLLECTION_ACTION';
// export const REMOVE_TABLES_ACTION = 'app/CollectionView/REMOVE_TABLES_ACTION';
// export const MOVE_TABLES_ACTION = 'app/CollectionView/MOVE_TABLES_ACTION';
